### PR TITLE
Fix anki.po:643: 'msgid' and 'msgstr' entries do not both end with '\n'

### PR DESCRIPTION
**Pull request by evandrocoan**
https://anki.tenderapp.com/discussions/beta-testing/1813-ankipo643-msgid-and-msgstr-entries-do-not-both-end-with-n

### CODE REVIEW

**Comment by evandrocoan** [comment]
Why the tests for this repository where passing with this error?

**Comment by evandrocoan** [comment]
I just confirmed, the error `msgfmt: found 1 fatal error` is not stopping the build process from continuing. This is why it was not failing before.

**Comment by dae** [comment]
I have applied a fix to the anki repo which should fix the error. For future reference, you'd need to adjust msgstr, not msgid to avoid breaking the translation.

**Comment by evandrocoan** [comment]
Sorry, I did not know it. Thanks for fixing it!

**Pull request closed without merging**
